### ISSUE TITLE
Little damage Leviathan doomsday (not damage per second)

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#157]
![image](https://user-images.githubusercontent.com/28200882/31863257-f967de58-b753-11e7-92d7-5aa2913b83c3.png)

**Comment by smudge202** [comment]
So I'm taking a look at this for you and observed the following differences between the various Doomsday weapons. Note, each race has two doomsdays, one for the *Titan* version of the Titan, the other for the *Capital* version of the Titan (this is because the two have a different `levelSourceType`):

Name | Titan / Capital | AI Usage | Autocast
--- | --- | --- | ---
Aurora | Titan | Any Time | ✓
Aurora | Capital | Any Time | ✓
Gjallarhorn | Titan | Combat Only | ✕
Gjallarhorn | Capital | Combat Only | ✕
Judgement | Titan | Any Time | ✓
Judgement | Capital | Any Time | ✓
Oblivion | Titan | Combat Only | ✕
Oblivion | Capital | Combat Only | ✕

In addition, the Oblivion for the *Titan* Titan does not improve as you level it (all other doomsdays reduce cooldown by 20 secs but the Titan version of Oblivion remains at 300).

I need to follow some string IDs back, but either vanilla IDs have been reused or some of the doomsdays have bad descriptions...

Anyway, I can fix any and all of the above, but as you can see, there appears to be two options to go for. Which is *correct*?

**Comment by Joeyxxx** [comment]
I see no reason why they should not default to Any Time - Autocast enabled.

**Comment by smudge202** [comment]
Ok cool; I don't know there's a functional change in-game between "Combat Only" and "Any Time" but I agree with the autocast. I've reworked the Leviathan doomsday so that it should have all the effects that @kabivel has put in, but damage is on par with other doomsdays. I need to do some further testing today and tomorrow but I'll get a PR in this week if no one else beats me to it, and I'll include aligning the doomsday stats shown above..

**Comment by kabivel** [comment]
oblivion do damage 4 times, dont know if what is showing is only for 1 hit or all

**Comment by kabivel** [comment]
fixed
