### ISSUE TITLE
Gallente Repair platform research

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#180]
The Gallente(others?) research 'Repair Platform' also unlocks a hangar bay and a building with a rather long name: 
![20171025163437_1](https://user-images.githubusercontent.com/32543932/32004584-68108936-b9a2-11e7-82fd-86df0aaf5e69.jpg)

It also has the icon for the Advent repair platform.
![20171024173018_1](https://user-images.githubusercontent.com/32543932/32004633-8d188c1a-b9a2-11e7-97f4-d415bef22f5f.jpg)

**Comment by smudge202** [comment]
Ref #163

**Comment by Joeyxxx** [comment]
![image](https://user-images.githubusercontent.com/32372181/32041958-f246f2d0-ba2d-11e7-90ea-26709bd3a132.png)

**Comment by smudge202** [comment]
^ This is fixed in the AI branch, however, playing Minmatar last night on Ai_Revamp branch (4e74c72651fdc31973a2fb178bcc2d8d20efd69c) I noticed that, after researching, Repair Platform was actually a Hanger Bay, and Hanger Bay was completely unavailable. I believe the same will be true for master as of PR #177 if someone can confirm?

**Comment by Joeyxxx** [comment]
@kabivel could you look into this?

**Comment by kabivel** [comment]
plataforms have new names and new icons
