### ISSUE TITLE
Black Ops Battleships & Cloaking mechanic

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#186]
Due to the limitations of the Sins engine and how we're dealing with cyno's/jump bridges/titan bridges I suggest that we make some changes to the cloaking mechanic.

Firstly, the cloaking mechanic. Immortal ships that you can do nothing about can be frustrating in a competitive RTS. I suggest that the Cloak ability is changed to a cycle, with a short break in between usage. 

For example; the cloak effect lasts 360 seconds but the ability cool down is 370 seconds. 

This will give a vigilant player a chance to destroy the cloaked ship. If everybody can see every system with no risk, then it removes the majority of tactics from the game - which turns it into a boring brawl.

__

The jump bridge skill should be removed from the Black Ops battleships. Unfortunately there is no way to make this work as it should. Due to these limitations you can uncloak your immortal black ops ship and light a cyno which your entire fleet can use.

**Comment by TempusLupus** [comment]
Cloaked Ships should be uncloaked if their cap is 0/neuted out which makes them targetable and be destroyed
I agree with everything else

**Comment by Joeyxxx** [comment]
Actually, that highlights a bug. Being able to use abilities on cloaked ships.

**Comment by TempusLupus** [comment]
To be honest all races should have some sort of ship with a neut, to make it only amarr is just unfair in my opinion

**Comment by Joeyxxx** [comment]
Do you not think that simply adding a cool down on the cloak ability would have the exact same outcome? This would avoid having to add Neuts to other ships.

**Comment by TempusLupus** [comment]
True, but then again. you'd have to micro manage a cloaky ship

**Comment by Jer0men** [comment]
Off topic: :p neuts on other ships and races could come in the form of some pirate ships having them.

Maybe add a cool down on the cloak to 20 seconds, long enough for a defended planets defences to respond accordingly. But if you're microing your cloaky ship at least make it viable to survive.

**Comment by Joeyxxx** [comment]
@TempusLupus I think if you want to scout and gather intel, you should have to work for it in the form of micro managing ships. Intel shouldn't be free in a **strategy** game.

@Jer0men I agree, a slightly longer cool down may work well. I also agree that some of the pirate ships may benefit from neuts - we'd need to figure out which one from each race could use them.

**Comment by smudge202** [comment]
Consider the eve mechanics regarding cloaking. Cloaked ships can sit anywhere, watching anything, with near immunity. The only time a cloaked ship uncloaks is when it jumps. You could Disable Phase Jump whilst cloak is active which would force the player to decloak in order to jump.

In eve, the only way to catch these guys is to gate camp (place large fleet on the inbound of a phase lane would achieve the same). Several small turrets may be able to achieve the same unless the ship gets it's cloak active quickly.

Admittedly, in Eve, you can decloak those ships by moving within 2500m (last I checked) but the chance of doing so is so low that people wouldn't even attempt it for a cov-ops.

Anyway, the point is, the cloak mechanics right now are about as closely inline with Eve as they can be (bar the phase jump disabling). They're a nuisance and provide intel. Their abilities don't do any harm at all so not being able to disable them while the cloak is active is a minor really.

**Comment by Joeyxxx** [comment]
Disabling phase jump is absolutely another solution, good idea. In fact, I think I prefer this alternative.

I do agree that it's inline with Eve, however there are other considerations such as I cannot log my fleet out or hide in safe spots etc. In Sins, this removes any element of sneak attacks and secret fleets/ships etc.

You're right, it warrants another thread for discussion - to be honest I didn't expect anybody to get involved.

**Comment by smudge202** [comment]
I haven't used cynos and jump bridges extensively in Sins yet, but I want to be able to and I want it to be balanced. Definitely subjects worthy of discussion! It's one of the key things I think that distinguishes this mod from others/vanilla.

Disabling the phase jump is a 1-liner, if @kabivel doesn't throw it in before me I'll get it PR'd. I vote we try that for now and see how it effects meta before proposing much else?

**Comment by BlodBladelicker** [comment]
One big issue with the current cloak and the Nestor. The nestor has the cloak ability from black ops, but doesn't lose its ability to use abilities while cloaked. Making it an invulnerable Logi ship.
![20171024182104_1](https://user-images.githubusercontent.com/32543932/32049831-d953fe5a-ba4e-11e7-91e0-b7699a4473a7.jpg)

**Comment by smudge202** [comment]
Hmmm, fair point. I think any ship that can cloak will need any abilities to interact remotely removed. Real pain that abilities can't be disabled while cloak is active!

**Comment by BlodBladelicker** [comment]
I think the cloak is the weird thing there. Not the reps. Ever seen a black ops fitted nestor? I only see them used as remote rep/cap platforms.

**Comment by smudge202** [comment]
True, Astero should have cloak, Nestor probably not.

**Comment by Joeyxxx** [comment]
@BlodBladelicker I hadn't noticed that the Nestor has a cloak - go ahead and bug that.

@smudge202 disabling phase jump may not be enough. Once the ship lands it could immediately cloak giving the opposing player only moments to attack the ship. The cloak ability would need a cool down, no?

**Comment by smudge202** [comment]
I don't think so, @Joeyxxx . And consider that the same mechanic is present in Eve. You arrive in new system (after jumping) inside a jump cloak for up to 30 seconds. As soon as you move your ship you drop the jump-cloak but can immediately use your ship cloak. Practised covert ops players will barely blink on the overview of an observer as the two cloaks swap over.

Jumping out is similar because by getting close enough to the gate to jump you automatically move within the 2500m limit that automatically deactivates the system cloak. But the gap between landing on a gate, decloaking, and initiating jump is so incredibly small, targeting the ship is impossible unless the covert ops pilots messes up.

Now imagine disabled jumps in Sins (no cooldown changes)...

Player arrives in system and has to click cloak. You're actually at a disadvantage here because in Eve you'd arrive in cloak and have 30 second leeway to have a think about your next move before you're forced out of jump cloak.

To get out of a system, you need to position yourself in the correct place to jump out and make sure your ship is facing the right way, before decloaking and then clicking your jump destination. Again, compared to Eve, you're at a disadvantage compared to just having clicked jump from anywhere in the system which would automatically perform the warp, decloak, and jump in one smooth movement. And that's ignoring the fact that in Eve you're only managing a single ship (unless multi-boxing). Not many RTA players will have/make the time to micro-manage this to such a fine degree, but will be rewarded if they do.

I think it's worth trying. Compared to any other ship in *Sins*, yes, Cov-Ops are going to be annoying. But compared to Eve, it's considerably more tedious.

**Comment by Joeyxxx** [comment]
You've convinced me, I'm on board.
